using System;
using System.Collections.Generic;

namespace SkillBuilderPro.WinForms.Models
{
    /// <summary>
    /// Represents a full training schedule for one athlete.
    /// Generated by DrillDatabase.GenerateTrainingSchedule() and stored
    /// in MainForm.cs as the private field: currentSchedule
    /// </summary>
    public class TrainingSchedule
    {
        /// <summary>Full name of the athlete this schedule belongs to</summary>
        public string AthleteName { get; set; }

        /// <summary>Sport the schedule is built for (drives which drills appear)</summary>
        public string Sport { get; set; }

        /// <summary>Timestamp when this schedule was generated</summary>
        public DateTime DateCreated { get; set; }

        /// <summary>
        /// The list of scheduled drill items.
        /// Each item = one row in the scheduleGrid DataGridView.
        /// Accessed in MainForm.cs:
        ///     foreach (var item in currentSchedule.Items)
        /// </summary>
        public List<ScheduleItem> Items { get; set; } = new List<ScheduleItem>();
    }
}
