using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using SkillBuilderPro.MAUI.Models;
using SkillBuilderPro.MAUI.Services;
using CoreDrill=SkillBuilderPro.Core.Models.Drill;
namespace SkillBuilderPro.MAUI.ViewModels;
public abstract partial class LoadableViewModel:ObservableObject
{
 [ObservableProperty] bool isBusy; [ObservableProperty] string? errorMessage; public bool HasError=>!string.IsNullOrWhiteSpace(ErrorMessage);
 protected async Task LoadGuard(Func<Task> work){if(IsBusy)return;IsBusy=true;ErrorMessage=null;try{await work();}catch{ErrorMessage="We couldn't load this right now. Please try again.";}finally{IsBusy=false;OnPropertyChanged(nameof(HasError));}}
}
public partial class DashboardViewModel(IAthleteApiService api):LoadableViewModel
{
 [ObservableProperty] Progression? progression; [ObservableProperty] int unreadCount; public bool HasUnread=>UnreadCount>0; public bool HasUnreadNotifications=>HasUnread; public string DisplayName=>api.IsDemoMode?DemoDataService.DisplayName:api.User?.FullName??"Athlete";public string AthleteDescriptor=>$"{(api.IsDemoMode?DemoDataService.Sport:api.User?.Sport??"ATHLETE").ToUpper()} ATHLETE  •  {Progression?.OverallRank?.ToUpper()??"DEVELOPING"}";public string TrainingTitle=>api.IsDemoMode?"HITTING DEVELOPMENT":Assignments.FirstOrDefault()?.Drill.Name?.ToUpper()??"NO TRAINING ASSIGNED";public string TrainingSummary=>api.IsDemoMode?"TIMING & BAT PATH  •  3 DRILLS  •  25 MINUTES":Assignments.FirstOrDefault()?.Instructions??"Your next assignment will appear here.";public string TrainingStatus=>Assignments.FirstOrDefault()?.RecipientStatus?.ToUpper()??"CLEAR"; partial void OnUnreadCountChanged(int value){OnPropertyChanged(nameof(HasUnread));OnPropertyChanged(nameof(HasUnreadNotifications));} public ObservableCollection<Goal> Goals{get;}=[];public ObservableCollection<AthleteAssignment> Assignments{get;}=[];
 [RelayCommand] async Task Load()=>await LoadGuard(async()=>{if(api.IsDemoMode){Progression=DemoDataService.Progression;Goals.Reset(DemoDataService.Goals);Assignments.Reset(DemoDataService.Assignments);UnreadCount=DemoDataService.UnreadNotifications;}else{Progression=await api.GetAsync<Progression>("api/athlete/progression");var goals=await api.GetAsync<List<Goal>>("api/athlete/goals")??[];Goals.Reset(goals.Where(x=>x.Status=="Active").Take(3));var assignments=await api.GetAsync<List<AthleteAssignment>>("api/athlete/assignments")??[];Assignments.Reset(assignments.Where(x=>x.RecipientStatus!="Completed").Take(3));var count=await api.GetAsync<UnreadCount>("api/athlete/notifications/unread-count");UnreadCount=count?.UnreadCountValue??0;}OnPropertyChanged(nameof(DisplayName));OnPropertyChanged(nameof(AthleteDescriptor));OnPropertyChanged(nameof(TrainingTitle));OnPropertyChanged(nameof(TrainingSummary));OnPropertyChanged(nameof(TrainingStatus));});
}
public partial class GoalsViewModel(IAthleteApiService api):LoadableViewModel
{
 [ObservableProperty] Progression? progression;public ObservableCollection<Goal> Active{get;}=[];public ObservableCollection<Goal> Completed{get;}=[];public Goal? Focus=>Active.FirstOrDefault();
 [RelayCommand] async Task Load()=>await LoadGuard(async()=>{if(api.IsDemoMode){Progression=DemoDataService.Progression;Active.Reset(DemoDataService.Goals.Where(x=>x.Status=="Active"));Completed.Reset(DemoDataService.Goals.Where(x=>x.Status=="Completed"));OnPropertyChanged(nameof(Focus));return;}Progression=await api.GetAsync<Progression>("api/athlete/progression");var all=await api.GetAsync<List<Goal>>("api/athlete/goals")??[];Active.Reset(all.Where(x=>x.Status=="Active"));Completed.Reset(all.Where(x=>x.Status=="Completed"));OnPropertyChanged(nameof(Focus));});
}
public partial class TrophyViewModel(IAthleteApiService api):LoadableViewModel
{[ObservableProperty] TrophyRoom? room;public ObservableCollection<Goal> Goals{get;}=[];public int AchievementCount=>Room?.Achievements.Count(x=>x.IsEarned)??0;public int MilestoneCount=>api.IsDemoMode?12:Room?.SkillMilestones.Count??0;public string RecentUnlock=>Room?.Achievements.Where(x=>x.IsEarned).OrderByDescending(x=>x.EarnedAtUtc).FirstOrDefault()?.Name??"No unlocks yet";public double RankProgress=>(Room?.CurrentProgression.ProgressToNextRank??0)/100d;public string NextRankLabel=>$"NEXT: {Room?.CurrentProgression.NextRank?.ToUpper()??"RANK PENDING"}";public string MilestoneSummary=>api.IsDemoMode?"Timing Builder · Hitting Development":Room?.SkillMilestones.OrderByDescending(x=>x.EarnedAtUtc).FirstOrDefault()?.LevelName??"No earned skill milestones";public string NextMilestone=>api.IsDemoMode?"COMPLETE 25 TRAINING SESSIONS":Room?.CurrentProgression.NextRank is {Length:>0} rank?$"REACH {rank.ToUpper()}":"CONTINUE QUALIFYING TRAINING";[RelayCommand]async Task Load()=>await LoadGuard(async()=>{if(api.IsDemoMode){Room=DemoDataService.Trophy;Goals.Reset(DemoDataService.Goals);}else{Room=await api.GetAsync<TrophyRoom>("api/athlete/trophy-room");Goals.Reset((await api.GetAsync<List<Goal>>("api/athlete/goals")??[]).Where(x=>x.Status=="Active").Take(2));}OnPropertyChanged(nameof(AchievementCount));OnPropertyChanged(nameof(MilestoneCount));OnPropertyChanged(nameof(RecentUnlock));OnPropertyChanged(nameof(RankProgress));OnPropertyChanged(nameof(NextRankLabel));OnPropertyChanged(nameof(MilestoneSummary));OnPropertyChanged(nameof(NextMilestone));});}
public partial class TrainingViewModel(IAthleteApiService api,ISportVisualService visuals):LoadableViewModel
{
 readonly List<CoreDrill> allDrills=[];
 string? requestedSport;
 public ObservableCollection<AthleteAssignment> Active{get;}=[]; public ObservableCollection<AthleteAssignment> Completed{get;}=[];
 public ObservableCollection<CoreDrill> Drills{get;}=[]; public ObservableCollection<string> Sports{get;}=[]; public ObservableCollection<string> Categories{get;}=[]; public ObservableCollection<string> SubCategories{get;}=[];
 [ObservableProperty]CoreDrill? selectedDrill; [ObservableProperty]string? selectedSport; [ObservableProperty]string? selectedCategory; [ObservableProperty]string? selectedSubCategory; [ObservableProperty]string background="strength_training.png";
 public void SetRequestedSport(string? sport){requestedSport=visuals.SupportedSports.FirstOrDefault(x=>string.Equals(x,sport,StringComparison.OrdinalIgnoreCase));if(requestedSport is not null&&Sports.Count>0)SelectedSport=Sports.FirstOrDefault(x=>string.Equals(x,requestedSport,StringComparison.OrdinalIgnoreCase))??requestedSport;}
 partial void OnSelectedSportChanged(string? value){Background=visuals.GetTrainingBackground(value);SelectedCategory=null;SelectedSubCategory=null;RefreshFilters();}
 partial void OnSelectedCategoryChanged(string? value){SelectedSubCategory=null;RefreshFilters();}
 partial void OnSelectedSubCategoryChanged(string? value)=>RefreshDrills();
 void RefreshFilters(){var sportRows=allDrills.Where(x=>string.IsNullOrWhiteSpace(SelectedSport)||string.Equals(x.Sport,SelectedSport,StringComparison.OrdinalIgnoreCase)).ToList();Categories.Reset(sportRows.Select(x=>x.Category).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).Order());var categoryRows=sportRows.Where(x=>string.IsNullOrWhiteSpace(SelectedCategory)||string.Equals(x.Category,SelectedCategory,StringComparison.OrdinalIgnoreCase));SubCategories.Reset(categoryRows.Select(x=>x.SubCategory).Where(x=>!string.IsNullOrWhiteSpace(x)).Select(x=>x!).Distinct(StringComparer.OrdinalIgnoreCase).Order());RefreshDrills();}
 void RefreshDrills(){Drills.Reset(allDrills.Where(x=>(string.IsNullOrWhiteSpace(SelectedSport)||string.Equals(x.Sport,SelectedSport,StringComparison.OrdinalIgnoreCase))&&(string.IsNullOrWhiteSpace(SelectedCategory)||string.Equals(x.Category,SelectedCategory,StringComparison.OrdinalIgnoreCase))&&(string.IsNullOrWhiteSpace(SelectedSubCategory)||string.Equals(x.SubCategory,SelectedSubCategory,StringComparison.OrdinalIgnoreCase))).OrderBy(x=>x.Name));if(SelectedDrill is not null&&!Drills.Any(x=>x.Id==SelectedDrill.Id))SelectedDrill=null;}
 [RelayCommand]void ClearSelection(){SelectedDrill=null;SelectedCategory=null;SelectedSubCategory=null;RefreshFilters();}
 [RelayCommand]async Task Load()=>await LoadGuard(async()=>{allDrills.Clear();IEnumerable<CoreDrill> source;if(api.IsDemoMode){source=DemoDataService.Drills;ErrorMessage=null;}else{source=await api.GetAsync<List<CoreDrill>>("api/drills")??[];ErrorMessage=api.IsServiceAvailable?null:api.ServiceStatusMessage;}allDrills.AddRange(source.Where(x=>YouTubeUrl.IsValid(x.VideoUrl)));if(api.IsDemoMode){Active.Reset(DemoDataService.Assignments);Completed.Reset([]);}else{var assignments=await api.GetAsync<List<AthleteAssignment>>("api/athlete/assignments")??[];Active.Reset(assignments.Where(x=>x.RecipientStatus!="Completed"));Completed.Reset(assignments.Where(x=>x.RecipientStatus=="Completed"));if(!api.IsServiceAvailable)ErrorMessage=api.ServiceStatusMessage;}Sports.Reset(allDrills.Select(x=>x.Sport).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).Order());var preferredSport=requestedSport??(api.IsDemoMode?DemoDataService.Sport:api.User?.Sport);SelectedSport=Sports.FirstOrDefault(x=>string.Equals(x,preferredSport,StringComparison.OrdinalIgnoreCase))??Sports.FirstOrDefault()??visuals.SupportedSports[0];Background=visuals.GetTrainingBackground(SelectedSport);RefreshFilters();if(api.IsDemoMode){SelectedCategory=Categories.FirstOrDefault();SelectedSubCategory=SubCategories.FirstOrDefault();SelectedDrill=Drills.FirstOrDefault();}OnPropertyChanged(nameof(HasError));});
}
public partial class RequestsViewModel(IAthleteApiService api):LoadableViewModel
{public ObservableCollection<TrainingRequestItem> Items{get;}=[];[RelayCommand]async Task Load()=>await LoadGuard(async()=>{if(api.IsDemoMode){Items.Reset([]);return;}Items.Reset(await api.GetAsync<List<TrainingRequestItem>>("api/athlete/training-requests")??[]);});}
public partial class NotificationsViewModel(IAthleteApiService api,ISportVisualService visuals):LoadableViewModel
{public ObservableCollection<NotificationItem> Items{get;}=[];[ObservableProperty]int unreadCount;[RelayCommand]async Task Load()=>await LoadGuard(async()=>{if(api.IsDemoMode){Items.Reset(DemoDataService.Notifications);UnreadCount=DemoDataService.UnreadNotifications;return;}var page=await api.GetAsync<NotificationPage>("api/athlete/notifications?page=1&pageSize=50");Items.Reset(page?.Items??[]);UnreadCount=page?.UnreadCount??0;});public async Task<string?> ResolveSportAsync(NotificationItem item){string text=$"{item.Title} {item.Message}";string[] sports=["Softball","Basketball","Baseball","Football","Soccer","Hockey","Strength"];var named=sports.FirstOrDefault(x=>text.Contains(x,StringComparison.OrdinalIgnoreCase));if(named is not null)return named;if(item.RelatedEntityId is int id&&item.RelatedEntityType?.Contains("Assignment",StringComparison.OrdinalIgnoreCase)==true){IEnumerable<AthleteAssignment> assignments=api.IsDemoMode?DemoDataService.Assignments:await api.GetAsync<List<AthleteAssignment>>("api/athlete/assignments")??[];var match=assignments.FirstOrDefault(x=>x.AssignmentId==id);if(!string.IsNullOrWhiteSpace(match?.Drill.Sport))return match.Drill.Sport;}return api.IsDemoMode?DemoDataService.Sport:api.User?.Sport;}[RelayCommand]async Task Read(NotificationItem item){if(item.IsRead||api.IsDemoMode)return;await api.PostAsync<NotificationItem>($"api/athlete/notifications/{item.NotificationId}/read");await Load();}[RelayCommand]async Task ReadAll(){if(api.IsDemoMode)return;await api.PostAsync<object>("api/athlete/notifications/read-all");await Load();}}
public partial class ProfileViewModel(IAthleteApiService api):ObservableObject
{
 [ObservableProperty]Progression? progression;[ObservableProperty]int activeGoalCount;
 public string DisplayName=>api.IsDemoMode?DemoDataService.DisplayName:api.User?.FullName??"Athlete";
 public string LockerNumber=>api.IsDemoMode?DemoDataService.LockerNumber:string.Empty;
 public bool HasLockerNumber=>!string.IsNullOrWhiteSpace(LockerNumber);
 public string Role=>api.IsDemoMode?"DEMO ATHLETE":api.User?.Roles.FirstOrDefault()?.ToUpper()??"ATHLETE";
 public string Sport=>api.IsDemoMode?DemoDataService.Sport:api.User?.Sport??"Sport not specified";
 public string Email=>api.IsDemoMode?"aubrey.demo@skillbuilderpro.local":api.User?.Email??"Not available";
 public string Phone=>api.IsDemoMode?"(312) 555-0138":api.User?.Phone??"Not available";
 public string Focus=>api.IsDemoMode?"Timing & Bat Path":api.User?.TargetArea??"Not specified";
 public string SkillLevel=>api.IsDemoMode?"Competitive":api.User?.ExperienceLevel??"Not specified";
 public string Team=>api.IsDemoMode?"Chicago Select Softball":"Not available";
 public string Status=>api.IsDemoMode?"DEMO ATHLETE":api.User?.IsActive==true?"ACTIVE":"INACTIVE";
 public string Bio=>api.IsDemoMode?"Contact-focused softball athlete building a repeatable swing, confident infield footwork, and consistent weekly training habits.":"Athlete bio is not available from the current authenticated profile contract.";
 public string ExitLabel=>api.IsDemoMode?"EXIT DEMO MODE":"SIGN OUT";
 public string NextMilestone=>api.IsDemoMode?"Complete 25 Training Sessions":Progression?.NextRank is {Length:>0} rank?$"Reach {rank}":"Continue qualifying training";
 [RelayCommand]async Task Load(){if(api.IsDemoMode){Progression=DemoDataService.Progression;ActiveGoalCount=DemoDataService.Goals.Length;}else{Progression=await api.GetAsync<Progression>("api/athlete/progression");ActiveGoalCount=(await api.GetAsync<List<Goal>>("api/athlete/goals")??[]).Count(x=>x.Status=="Active");}OnPropertyChanged(nameof(NextMilestone));}
 [RelayCommand]async Task Logout(){await api.LogoutAsync();Application.Current!.Windows[0].Page=new NavigationPage(new Views.ChooseProfilePage(api));}
}
static class CollectionExtensions{public static void Reset<T>(this ObservableCollection<T> target,IEnumerable<T> source){target.Clear();foreach(var item in source)target.Add(item);}}
