// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillBuilderPro.API.Data;

#nullable disable

namespace SkillBuilderPro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720174445_AddSubCategoryToDrill")]
    partial class AddSubCategoryToDrill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillBuilderPro.Core.Models.Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Drills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Dribbling",
                            Description = "5-minute dribbling workout that changes your game.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Ball Handling Drills",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=oADaM2L1YLc"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Shooting",
                            Description = "Find your perfect shooting form.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Shooting Form Basics",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=x7anDE7OEww"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Defense",
                            Description = "Three defense drills to make your team better.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Defensive Footwork",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=lFY__uSOJIY"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Rebounding",
                            Description = "Three best basketball rebounding drills that win games.",
                            DifficultyLevel = 1,
                            Duration = 20,
                            Name = "Rebounding Techniques",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=pFRlEOeWpKY"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Passing",
                            Description = "Three basketball drills to become better at passing.",
                            DifficultyLevel = 1,
                            Duration = 20,
                            Name = "Passing Accuracy",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=OUskjh1r4Aw"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Passing",
                            Description = "How to throw a football with Tom Brady.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Passing Technique",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=lv5p2Xqkxyk"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Catching",
                            Description = "WR drills with Odell Beckham Jr.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Catching Skills",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=4n-Js1SwC2c"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Route Running",
                            Description = "Cooper Kupp's WR drills for creating separation.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Route Running",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=b8Y-BrxoGQc"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Blocking",
                            Description = "Proper technique for run and pass blocking.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Blocking Fundamentals",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=hHyjR__k3XA"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Conditioning",
                            Description = "Ten speed and agility ladder drills.",
                            DifficultyLevel = 3,
                            Duration = 20,
                            Name = "Speed and Agility",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=9ZTRUVLjGzI"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Hitting",
                            Description = "Ten best softball hitting drills for kids.",
                            DifficultyLevel = 1,
                            Duration = 20,
                            Name = "Hitting Drills",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=g-yDDzQL6eE"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pitching",
                            Description = "Basic five steps for a beginner pitcher.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Pitching Mechanics",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=mIx9CvpGXsU"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Fielding",
                            Description = "Three infield drills for youth players.",
                            DifficultyLevel = 1,
                            Duration = 20,
                            Name = "Infield Drills",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=6z0cpY5nGMA"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Fielding",
                            Description = "Must-do outfield drills with Gold Glover AJ Andrews.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Outfield Skills",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=QREFQP72W0U"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Catching",
                            Description = "How to improve as a softball catcher.",
                            DifficultyLevel = 3,
                            Duration = 20,
                            Name = "Catcher Fundamentals",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=qwdeRteH3es"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Hitting",
                            Description = "Ten best baseball hitting drills for kids.",
                            DifficultyLevel = 1,
                            Duration = 20,
                            Name = "Hitting Drills",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=gOE484Meo_o"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Pitching",
                            Description = "Must-do youth baseball pitching drills.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Pitching Drills",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=McHb2hXrTrE"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Fielding",
                            Description = "The top four infield drills.",
                            DifficultyLevel = 1,
                            Duration = 20,
                            Name = "Infield Drills",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=Uj5lw17XvuI"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Fielding",
                            Description = "Baseball outfield drills you must be doing.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Outfield Drills",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=WUIM8NqNETg"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Catching",
                            Description = "How to become a better baseball catcher.",
                            DifficultyLevel = 3,
                            Duration = 20,
                            Name = "Catcher Training",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=KJZHdoPxvW0"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Skating",
                            Description = "Edge-work drills from level 1 to 100.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Edge-Work Skating",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=pp0Y3BDDp4A"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Dribbling",
                            Description = "Five-minute daily stickhandling routine.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Stickhandling Routine",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=7HluVwbAv3w"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Shooting",
                            Description = "Fifteen hockey shooting drills.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Shooting Drills",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=RrYFNdTNvkc"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Passing",
                            Description = "How to catch and receive passes.",
                            DifficultyLevel = 1,
                            Duration = 20,
                            Name = "Passing Technique",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=BFI7jzMgu6Q"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Defense",
                            Description = "How to play better defense in hockey.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Defensive Positioning",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=HkNAK40ugkw"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Dribbling",
                            Description = "Five essential dribbling drills.",
                            DifficultyLevel = 1,
                            Duration = 20,
                            Name = "Dribbling Drills",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=jwIHc9rz7yo"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Shooting",
                            Description = "Ten finishing exercises to become clinical.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Finishing Exercises",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=0u8kPwXXsLA"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Passing",
                            Description = "Ten best soccer passing drills.",
                            DifficultyLevel = 1,
                            Duration = 20,
                            Name = "Passing Drills",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=Kb58F3r_TQM"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Defense",
                            Description = "Stop getting beaten in one-on-one situations.",
                            DifficultyLevel = 2,
                            Duration = 20,
                            Name = "Defensive Fundamentals",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=aadebgx5nz4"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Conditioning",
                            Description = "Eight exercises to improve speed, agility and power.",
                            DifficultyLevel = 3,
                            Duration = 20,
                            Name = "Speed and Agility",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=cCZSTGeSuHM"
                        });
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.ProgressLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.ToTable("ProgressLogs");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.TrainingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TargetArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.ProgressLog", b =>
                {
                    b.HasOne("SkillBuilderPro.Core.Models.Drill", "Drill")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.TrainingSchedule", b =>
                {
                    b.HasOne("SkillBuilderPro.Core.Models.Drill", "Drill")
                        .WithMany("Schedules")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.Drill", b =>
                {
                    b.Navigation("ProgressLogs");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
