// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillBuilderPro.API.Data;

#nullable disable

namespace SkillBuilderPro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717153756_Add30DrillsWithYouTube")]
    partial class Add30DrillsWithYouTube
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillBuilderPro.Core.Models.Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Drills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Dribbling",
                            Description = "Improve handles with advanced dribbling techniques.",
                            DifficultyLevel = 2,
                            Name = "Ball Handling Drills",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=UVAz2aASZx4"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Shooting",
                            Description = "Master proper shooting technique and form.",
                            DifficultyLevel = 2,
                            Name = "Shooting Form Basics",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=hYaLYGmS61A"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Defense",
                            Description = "Learn proper defensive stance and movement.",
                            DifficultyLevel = 2,
                            Name = "Defensive Footwork",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Passing",
                            Description = "Develop precision passing and court vision.",
                            DifficultyLevel = 1,
                            Name = "Passing Accuracy",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Footwork",
                            Description = "Build explosive footwork and lateral agility.",
                            DifficultyLevel = 3,
                            Name = "Footwork Conditioning",
                            Sport = "Basketball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Passing",
                            Description = "Master offensive route running patterns.",
                            DifficultyLevel = 2,
                            Name = "Passing Routes",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Defense",
                            Description = "Learn proper tackling form and safety.",
                            DifficultyLevel = 2,
                            Name = "Tackling Technique",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Blocking",
                            Description = "Develop offensive line blocking fundamentals.",
                            DifficultyLevel = 2,
                            Name = "Line Blocking",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Ball Handling",
                            Description = "Prevent fumbles with strong ball security drills.",
                            DifficultyLevel = 1,
                            Name = "Ball Security",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Conditioning",
                            Description = "Build speed and endurance for game performance.",
                            DifficultyLevel = 3,
                            Name = "Conditioning Sprints",
                            Sport = "Football",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Hitting",
                            Description = "Perfect your stance and swing mechanics.",
                            DifficultyLevel = 1,
                            Name = "Batting Stance",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Running",
                            Description = "Improve speed and technique between bases.",
                            DifficultyLevel = 2,
                            Name = "Base Running",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Fielding",
                            Description = "Master ground ball and fly ball techniques.",
                            DifficultyLevel = 2,
                            Name = "Fielding Basics",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Pitching",
                            Description = "Learn proper pitching form and control.",
                            DifficultyLevel = 3,
                            Name = "Pitching Mechanics",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Throwing",
                            Description = "Develop arm strength and throwing precision.",
                            DifficultyLevel = 2,
                            Name = "Throwing Accuracy",
                            Sport = "Baseball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Hitting",
                            Description = "Tee placement and batting technique.",
                            DifficultyLevel = 2,
                            Name = "Softball Hitting Drills",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=ZxkrWk5j2NE"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Defense",
                            Description = "Learn proper fielding positions and angles.",
                            DifficultyLevel = 1,
                            Name = "Defensive Positioning",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Running",
                            Description = "Master safe and effective sliding into bases.",
                            DifficultyLevel = 2,
                            Name = "Sliding Technique",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Throwing",
                            Description = "Build arm strength with proper throwing form.",
                            DifficultyLevel = 2,
                            Name = "Throwing Fundamentals",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Catching",
                            Description = "Improve catching technique and pop time.",
                            DifficultyLevel = 3,
                            Name = "Catching Skills",
                            Sport = "Softball",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Dribbling",
                            Description = "Enhance touch and close ball control.",
                            DifficultyLevel = 2,
                            Name = "Ball Control",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Passing",
                            Description = "Master short and long range passing.",
                            DifficultyLevel = 1,
                            Name = "Passing Accuracy",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Shooting",
                            Description = "Improve shot power and accuracy toward goal.",
                            DifficultyLevel = 2,
                            Name = "Shooting Technique",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Defense",
                            Description = "Learn positioning and marking techniques.",
                            DifficultyLevel = 2,
                            Name = "Defensive Tactics",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Ball Control",
                            Description = "Develop soft first touch and ball reception.",
                            DifficultyLevel = 1,
                            Name = "First Touch",
                            Sport = "Soccer",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Dribbling",
                            Description = "Master puck control at speed.",
                            DifficultyLevel = 2,
                            Name = "Stick Handling",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Shooting",
                            Description = "Improve shot speed and placement.",
                            DifficultyLevel = 2,
                            Name = "Shooting Accuracy",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Defense",
                            Description = "Learn proper body checking form.",
                            DifficultyLevel = 3,
                            Name = "Checking Technique",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Passing",
                            Description = "Develop precision tape-to-tape passing.",
                            DifficultyLevel = 1,
                            Name = "Passing Drills",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Skating",
                            Description = "Build speed, balance, and edge work.",
                            DifficultyLevel = 3,
                            Name = "Skating Agility",
                            Sport = "Hockey",
                            VideoUrl = "https://www.youtube.com/watch?v=PLACEHOLDER"
                        });
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.ProgressLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.ToTable("ProgressLogs");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.TrainingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TargetArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.ProgressLog", b =>
                {
                    b.HasOne("SkillBuilderPro.Core.Models.Drill", "Drill")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.TrainingSchedule", b =>
                {
                    b.HasOne("SkillBuilderPro.Core.Models.Drill", "Drill")
                        .WithMany("Schedules")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.Drill", b =>
                {
                    b.Navigation("ProgressLogs");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
