// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillBuilderPro.API.Data;

#nullable disable

namespace SkillBuilderPro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillBuilderPro.Core.Models.Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasJsonPropertyName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasJsonPropertyName("difficulty");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("sport");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("videoUrl");

                    b.HasKey("Id");

                    b.HasIndex("Sport");

                    b.ToTable("Drills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "",
                            Description = "5-minute dribbling workout",
                            Difficulty = 2,
                            Name = "Ball Handling Drills",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            Category = "",
                            Description = "Find your perfect shooting form",
                            Difficulty = 2,
                            Name = "Shooting Form Basics",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 3,
                            Category = "",
                            Description = "Three defense drills",
                            Difficulty = 2,
                            Name = "Defensive Footwork",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            Category = "",
                            Description = "Basketball rebounding drills",
                            Difficulty = 1,
                            Name = "Rebounding Techniques",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            Category = "",
                            Description = "Drills to become better at passing",
                            Difficulty = 1,
                            Name = "Passing Accuracy",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 6,
                            Category = "",
                            Description = "Transition offense drills",
                            Difficulty = 3,
                            Name = "Fast Break Drills",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 7,
                            Category = "",
                            Description = "Low post fundamentals",
                            Difficulty = 2,
                            Name = "Post Moves",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 8,
                            Category = "",
                            Description = "Long range shooting drills",
                            Difficulty = 3,
                            Name = "Three Point Shooting",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 9,
                            Category = "",
                            Description = "Advanced ball handling",
                            Difficulty = 3,
                            Name = "Crossover Dribble",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 10,
                            Category = "",
                            Description = "Passing technique drills",
                            Difficulty = 1,
                            Name = "Bounce Pass Drills",
                            Sport = "Basketball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 11,
                            Category = "",
                            Description = "Throwing mechanics",
                            Difficulty = 2,
                            Name = "Passing Technique",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 12,
                            Category = "",
                            Description = "WR drills",
                            Difficulty = 2,
                            Name = "Catching Skills",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 13,
                            Category = "",
                            Description = "Creating separation",
                            Difficulty = 2,
                            Name = "Route Running",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 14,
                            Category = "",
                            Description = "Run and pass blocking",
                            Difficulty = 2,
                            Name = "Blocking Fundamentals",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 15,
                            Category = "",
                            Description = "Ladder drills",
                            Difficulty = 3,
                            Name = "Speed and Agility",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 16,
                            Category = "",
                            Description = "QB footwork",
                            Difficulty = 2,
                            Name = "Footwork Drills",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 17,
                            Category = "",
                            Description = "Pass rush drills",
                            Difficulty = 3,
                            Name = "Edge Rusher Technique",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 18,
                            Category = "",
                            Description = "Defensive back drills",
                            Difficulty = 2,
                            Name = "Coverage Drills",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 19,
                            Category = "",
                            Description = "Proper tackling form",
                            Difficulty = 2,
                            Name = "Tackling Drills",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 20,
                            Category = "",
                            Description = "Agility cone drills",
                            Difficulty = 1,
                            Name = "Cone Drills",
                            Sport = "Football",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 21,
                            Category = "",
                            Description = "Batting practice",
                            Difficulty = 1,
                            Name = "Hitting Drills",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 22,
                            Category = "",
                            Description = "Windmill pitch",
                            Difficulty = 2,
                            Name = "Pitching Mechanics",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 23,
                            Category = "",
                            Description = "Ground ball drills",
                            Difficulty = 1,
                            Name = "Infield Drills",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 24,
                            Category = "",
                            Description = "Fly ball drills",
                            Difficulty = 2,
                            Name = "Outfield Skills",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 25,
                            Category = "",
                            Description = "Catching drills",
                            Difficulty = 3,
                            Name = "Catcher Fundamentals",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 26,
                            Category = "",
                            Description = "Bunting drills",
                            Difficulty = 2,
                            Name = "Bunting Techniques",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 27,
                            Category = "",
                            Description = "Running drills",
                            Difficulty = 1,
                            Name = "Base Running",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 28,
                            Category = "",
                            Description = "Pitcher drills",
                            Difficulty = 2,
                            Name = "Drop Ball Drill",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 29,
                            Category = "",
                            Description = "Throwing accuracy",
                            Difficulty = 2,
                            Name = "Relay Throws",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 30,
                            Category = "",
                            Description = "Base sliding",
                            Difficulty = 1,
                            Name = "Sliding Drills",
                            Sport = "Softball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 31,
                            Category = "",
                            Description = "Batting practice",
                            Difficulty = 1,
                            Name = "Hitting Drills",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 32,
                            Category = "",
                            Description = "Youth pitching drills",
                            Difficulty = 2,
                            Name = "Pitching Drills",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 33,
                            Category = "",
                            Description = "Ground ball drills",
                            Difficulty = 1,
                            Name = "Infield Drills",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 34,
                            Category = "",
                            Description = "Fly ball drills",
                            Difficulty = 2,
                            Name = "Outfield Drills",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 35,
                            Category = "",
                            Description = "Catcher drills",
                            Difficulty = 3,
                            Name = "Catcher Training",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 36,
                            Category = "",
                            Description = "Running drills",
                            Difficulty = 1,
                            Name = "Base Running",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 37,
                            Category = "",
                            Description = "Breaking ball drills",
                            Difficulty = 3,
                            Name = "Curveball Practice",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 38,
                            Category = "",
                            Description = "Relay throw drills",
                            Difficulty = 2,
                            Name = "Cut-off Throws",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 39,
                            Category = "",
                            Description = "Infield coordination",
                            Difficulty = 2,
                            Name = "Double Play Drills",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 40,
                            Category = "",
                            Description = "Base sliding",
                            Difficulty = 1,
                            Name = "Slide Drills",
                            Sport = "Baseball",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 41,
                            Category = "",
                            Description = "Skating drills",
                            Difficulty = 2,
                            Name = "Edge-Work Skating",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 42,
                            Category = "",
                            Description = "Dribbling drills",
                            Difficulty = 2,
                            Name = "Stickhandling Routine",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 43,
                            Category = "",
                            Description = "Shot accuracy",
                            Difficulty = 2,
                            Name = "Shooting Drills",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 44,
                            Category = "",
                            Description = "Passing drills",
                            Difficulty = 1,
                            Name = "Passing Technique",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 45,
                            Category = "",
                            Description = "Defense drills",
                            Difficulty = 2,
                            Name = "Defensive Positioning",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 46,
                            Category = "",
                            Description = "Skating technique",
                            Difficulty = 2,
                            Name = "Crossover Drill",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 47,
                            Category = "",
                            Description = "Shooting on the move",
                            Difficulty = 3,
                            Name = "One-Timer Practice",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 48,
                            Category = "",
                            Description = "Body checking drills",
                            Difficulty = 2,
                            Name = "Checking Drills",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 49,
                            Category = "",
                            Description = "Goaltending drills",
                            Difficulty = 3,
                            Name = "Goalie Drills",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 50,
                            Category = "",
                            Description = "Endurance skating",
                            Difficulty = 2,
                            Name = "Conditioning Skate",
                            Sport = "Hockey",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 51,
                            Category = "",
                            Description = "Ball control drills",
                            Difficulty = 1,
                            Name = "Dribbling Drills",
                            Sport = "Soccer",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 52,
                            Category = "",
                            Description = "Shooting drills",
                            Difficulty = 2,
                            Name = "Finishing Exercises",
                            Sport = "Soccer",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 53,
                            Category = "",
                            Description = "Passing technique",
                            Difficulty = 1,
                            Name = "Passing Drills",
                            Sport = "Soccer",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 54,
                            Category = "",
                            Description = "Defense drills",
                            Difficulty = 2,
                            Name = "Defensive Fundamentals",
                            Sport = "Soccer",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 55,
                            Category = "",
                            Description = "Speed drills",
                            Difficulty = 3,
                            Name = "Speed and Agility",
                            Sport = "Soccer",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 56,
                            Category = "",
                            Description = "Wing play drills",
                            Difficulty = 2,
                            Name = "Crossing Drills",
                            Sport = "Soccer",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 57,
                            Category = "",
                            Description = "Free kick drills",
                            Difficulty = 3,
                            Name = "Free Kick Practice",
                            Sport = "Soccer",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 58,
                            Category = "",
                            Description = "Heading technique",
                            Difficulty = 2,
                            Name = "Heading Drills",
                            Sport = "Soccer",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 59,
                            Category = "",
                            Description = "Ball control drills",
                            Difficulty = 1,
                            Name = "First Touch Drills",
                            Sport = "Soccer",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 60,
                            Category = "",
                            Description = "Formation drills",
                            Difficulty = 2,
                            Name = "Tactical Drills",
                            Sport = "Soccer",
                            VideoUrl = ""
                        });
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.ProgressLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<int?>("DrillId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrillId1");

                    b.HasIndex("DrillId", "LogDate");

                    b.ToTable("ProgressLogs");

                    b.HasAnnotation("Relational:JsonPropertyName", "progressLogs");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.TrainingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<int?>("DrillId1")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.HasIndex("DrillId1");

                    b.ToTable("Schedules");

                    b.HasAnnotation("Relational:JsonPropertyName", "schedules");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TargetArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.ProgressLog", b =>
                {
                    b.HasOne("SkillBuilderPro.Core.Models.Drill", null)
                        .WithMany()
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBuilderPro.Core.Models.Drill", "Drill")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("DrillId1");

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.TrainingSchedule", b =>
                {
                    b.HasOne("SkillBuilderPro.Core.Models.Drill", null)
                        .WithMany()
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBuilderPro.Core.Models.Drill", "Drill")
                        .WithMany("Schedules")
                        .HasForeignKey("DrillId1");

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("SkillBuilderPro.Core.Models.Drill", b =>
                {
                    b.Navigation("ProgressLogs");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
